// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmgCpAcEbM9g6EYm2NEBfgc6SahuZzNZ8',
    appId: '1:544258976640:web:390c32459b76bd6510af65',
    messagingSenderId: '544258976640',
    projectId: 'chatting-7a5e5',
    authDomain: 'chatting-7a5e5.firebaseapp.com',
    storageBucket: 'chatting-7a5e5.firebasestorage.app',
    measurementId: 'G-GDJHSLV1GY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAINHxMHVJVXuxLIyvx8CGvBXP12BMXT3o',
    appId: '1:544258976640:android:b5bb70547b76f40d10af65',
    messagingSenderId: '544258976640',
    projectId: 'chatting-7a5e5',
    storageBucket: 'chatting-7a5e5.firebasestorage.app',
  );
}
